### PR TITLE
Fix receive method

### PR DESCRIPTION
**Pull request by MartinHjelmare**
Hi!

Thanks for the matrixscreener API! Here's something I needed to do to be able to change the PMT gain, for example.

This fix ensures that the server and microscope has time to finish a
command and return a reply, before method receive returns. Some
commands, like change of PMT gain, can take a while to excecute for the
microscope. Start scan command also takes a while before the server
returns a reply.
- Add method _check_socket to check if socket is readable using select.
- Use _check_socket in method receive until socket is readable or after
  timeout of 10 seconds. When socket is readable, call recv on socket.
- Fix PEP issues in cam module.
- Fix docstrings in cam module.
- Add method fileno to mock socket class, in test_cam module, and make
  select work during tests.
- Fix some, but not all, PEP issues in test_cam module.

Best regards,
Martin

### CODE REVIEW

**Comment by arve0** [comment]
Hi, thanks for the PR. Have you seen https://github.com/arve0/leicacam

**Comment by MartinHjelmare** [comment]
I had a quick look and thought it was an older version. I guess I was wrong. I see you have the wait_for method there. Nice! The dev environment also look more feature full, Travis etc. I'll probably use that instead then. Thanks!

If you don't want to merge this, that's fine either way.

**Comment by arve0** [comment]
I do not mind merging, but I'm not at the computer now. I'll have a look at your PR later. If you want I can also point to your fork, if you're interested in maintaining? I do no longer have access to the microscope..

**Comment by MartinHjelmare** [comment]
I'll try to maintain my fork, but the only way to keep the RTD docs updated are through PRs to the upstream repo, right? I don't know that I would make any major changes right now though.

**Comment by arve0** [comment]
> but the only way to keep the RTD docs updated are through PRs to the upstream repo, right?

Yes, you are correct. Also, the package needs to be released to pypi. If you're using this software, I suggest that I'll transfer/release the names on pypi and read the docs, so that you can fully control all the aspects.

**Comment by arve0** [comment]
Released in [v0.6.1](https://pypi.python.org/pypi?name=matrixscreener&:action=display).

**Comment by MartinHjelmare** [comment]
You could transfer ownership to me. The other option is to grant me push access to the repo and make me a maintainer on pypi. I haven't published yet to pypi, so I don't know all the ins and outs, but according their docs, that should work. Some settings will probably still be off limits without ownership, though. Btw, I'll have to delete my fork, before you can transfer ownership of the repo.

Thanks for merging.

**Comment by arve0** [comment]
Pypi have similar features. Send me your username at pypi, and I'll add you as a maintainer.

I've documented the current [release workflow](https://github.com/arve0/matrixscreener#release-procedure), which might need [simplifications](https://github.com/arve0/leicacam/blob/master/setup.py#L16).

**Pull request merged**
